name: Scrape Marketplace Data

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  push:
    branches:
      - main
    paths:
      - 'items.json'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py
        env:
          # GitHub Secrets에 저장한 값들을 환경 변수로 스크립트에 전달합니다.
          UPLAY_TOKEN: ${{ secrets.UPLAY_TOKEN }}
          UBI_SESSION_ID: ${{ secrets.UBI_SESSION_ID }}

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update marketplace data via official API"
          file_pattern: results.json
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>